### ISSUE TITLE
Setup a custom highlighter

### ISSUE THREAD

**Issue by danilopolani** [nartc/notion-stuff#11]
Hey,
first of all great package, thank you a lot!

I was trying to setup a different highlighter (`shiki`) but I always fail to. What's the proper way? I tried both of the following solutions, the first one complaining about the missing `highlight.js`; the second one complains that `callback` is not defined (although the [correct way of marked to handle async highlighters](https://marked.js.org/using_advanced#highlight)) and `Cannot read properties of undefined (reading language)` [here](https://github.com/nartc/notion-stuff/blob/main/libs/blocks-html-parser/src/lib/blocks-html-parser.ts#L113).

```ts
const markedOptions: markedType.MarkedOptions = {
  renderer: new marked.Renderer(),
  highlight: (code, lang, callback) => {
    shiki.getHighlighter({ theme: 'nord' }).then(highlighter => {
      callback(highlighter.codeToHtml(code, { lang }));
    })
  },
};

const markedOptions: markedType.MarkedOptions = {
  renderer: new marked.Renderer(),
  highlight: (code, lang, callback) => {
    shiki.getHighlighter({ theme: 'nord' }).then(highlighter => {
      callback(highlighter.codeToHtml(code, { lang }));
    })
  },
};

const parserOptions: NotionBlocksHtmlParserOptions = {
  mdParserOptions: {
    emptyParagraphToNonBreakingSpace: true,
  },
  mdToHtmlOptions: markedOptions, // Only with this: Error importing package: highlight.js.
  mdHighlightingOptions: markedOptions.highlight, // Cannot read properties of undefined (reading 'language')
};
```

**Comment by nartc** [comment]
Well, I screwed up my npm auth (just setup my new machine) and cannot publish new version at the moment. I'll publish it tomorrow. Sorry for the inconvenience

**Comment by danilopolani** [comment]
> Well, I screwed up my npm auth (just setup my new machine) and cannot publish new version at the moment. I'll publish it tomorrow. Sorry for the inconvenience

Don't worry, take your time! Thank you in advance for the quick response :)

**Comment by nartc** [comment]
v6 has been released
