### ISSUE TITLE
Property 'type' does not exist on type

### ISSUE THREAD

**Issue by TheCapedBaldi** [nartc/notion-stuff#7]
Hi there!

Unfortunately, I'm getting the following error on line 133. Any idea how this can be fixed?

```
Property 'type' does not exist on type '{ type: "emoji"; emoji: ...}`
```

https://github.com/nartc/notion-stuff/blob/6e22fbffafb528e41cc31258c34b5234048ebb25/libs/v4-types/src/lib/types.ts#L133

Even though the types technically exist:
<img width="697" alt="Screenshot 2021-11-09 at 11 26 49" src="https://user-images.githubusercontent.com/16179773/140916055-5413a298-5951-4568-84d2-a067a2ac94f3.png">

<img width="1228" alt="Screenshot 2021-11-09 at 11 27 05" src="https://user-images.githubusercontent.com/16179773/140916041-e7a585bf-4642-44ee-8bd1-f8114d8dfaa0.png">

**Comment by nartc** [comment]
What typescript version are you using?
![image](https://user-images.githubusercontent.com/25516557/140925866-bba959ef-5de7-40cb-97ea-2c09e898c36f.png)

**Comment by TheCapedBaldi** [comment]
`V4.4.4`

**Comment by TheCapedBaldi** [comment]
My file encoding format is in UTF-8. Can you please verify yours?

<img width="1117" alt="Screenshot 2021-11-09 at 13 11 10" src="https://user-images.githubusercontent.com/16179773/140930073-e199ee54-07c6-4373-9e65-1d706007c571.png">

**Comment by nartc** [comment]
![image](https://user-images.githubusercontent.com/25516557/140949993-43ad896c-5861-4d65-81fe-6d8e204e38cf.png)
Same :(

**Comment by TheCapedBaldi** [comment]
Can you perhaps share your TSConfig settings please?

**Comment by nartc** [comment]
Should be this one https://github.com/nartc/notion-stuff/blob/main/tsconfig.base.json

**Comment by TheCapedBaldi** [comment]
Great! I'll look into the project tonight. If I fix it, I'll close this ticket 🙏

**Comment by ajonp** [comment]
I believe I see the same...

```
node_modules/@notion-stuff/blocks-markdown-parser/node_modules/@notion-stuff/v4-types/src/lib/types.d.ts:95:51 - error TS2339: Property 'type' does not exist on type '{ type: "emoji"; emoji: "😀" | "😃" | "😄" | "😁" | "😆" | "😅" | "🤣" | "😂" | "🙂" | "🙃" | "😉" | "😊" | "😇" | "🥰" | "😍" | "🤩" | "😘" | "😗" | "☺️" | "☺" | "😚" | "😙" | "🥲" | "😋" | ... 3534 more ... | "🏴󠁧󠁢󠁷󠁬󠁳󠁿"; } | { ...; } | { ...; } | null'.

95 export declare type CalloutIconType = CalloutIcon['type'];
```

**Comment by nartc** [comment]
@ajonp Can I have a reproduce? :(

**Comment by TheCapedBaldi** [comment]
Unfortunately, I couldn't solve why there's a bug. I can clearly see the 'type' if I apply it on a variable:

```typescript
export type CalloutIcon = CalloutBlock['callout']['icon']

const foo: CalloutIcon = {
    // emoji
    // external
    // file
    // type
}

export type CalloutIconType = CalloutIcon['type'] // <= Error: Property 'type' does not exist on type
```

Not sure how I can help you reproduce this error since we're both relying on node modules

**Comment by TheCapedBaldi** [comment]
How does your VSCode recognise emoji from intellisense? Do you have a particular extension installed for emojis? Also what type of font are you using?

**Comment by TheCapedBaldi** [comment]
For the time being, I'm overriding it to fix the bug:

```typescript
export type CalloutIcon = CalloutBlock['callout']['icon'] & {
  icon: {
    type: 'emoji'
    emoji: 'string'
  }
}
```

**Comment by nartc** [comment]
@TheCapedBaldi I have just updated to `0.4.11` and ran into some typing issue. Check out the latest code in for details

**Comment by TheCapedBaldi** [comment]
Sure will look into it sometime Monday 👌

**Comment by brapifra** [comment]
Wrapping `CalloutIcon` with `NonNullable` fixes the issue:
```typescript
export type CalloutIconType = NonNullable<CalloutIcon>["type"]
```

**Comment by TheCapedBaldi** [comment]
@brapifra solution resolved my issue. closing this ticket 😉  Thanks for the help 🙏🏻
