### ISSUE TITLE
TS2339: Property 'properties' does not exist on type 'GetPageResponse'.

### ISSUE THREAD

**Issue by 0815pascal** [nartc/notion-stuff#9]
Hi everyone!

Not sure if I'm doing this right: I would like to extract the title of a given page but end up with some behavior that doesn't make sense to me. Here's the crucial part of my code so far: 

```
import {PropertyValueMap } from "@notion-stuff/v4-types";
(....)
const response  = await notion.pages.retrieve({ page_id: rootBlockId });
const properties: PropertyValueMap  = response.properties
console.log(response)
```

I've also tried using different types such as `PropertyValue`. Now the weird thing is that when printing `response` I would get 

```
{
  object: 'page',
  id: 'XXXXXX',
  (...)
  properties: { title: { id: 'title', type: 'title', title: [Array] } },
  url: 'https://www.notion.so/XXXXXXXX'
}
```
So `properties` clearly seems to be contained inside this object, however I would get the following error-message: 

```
TS2339: Property 'properties' does not exist on type 'GetPageResponse'.   
Property 'properties' does not exist on type '{ object: "page"; id: string; }'.
```

Why is this? I apologize if the answer is rather easy; I'm still wrapping my head around the more difficult parts of TypeScript.

**Comment by nartc** [comment]
Hi @0815pascal, thanks for reporting. This is to show how awful the Notion team’s decision on their Dev Experience is. 

The return type of pages.retrieve() is the problem here. You can cast that to PostResult to grab the properties 

const response = (await notion.pages.retrieve({…})) as PostResult;

const properties = response.properties;

**Comment by 0815pascal** [comment]
Thanks @nartc - that indeed did the job for me! :)
